apiVersion: apps/v1
kind: Deployment
metadata:
  name: domainmodels-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domainmodelservice
  template:
    metadata:
      labels:
        app: domainmodelservice
    spec:
      containers:
        - name: domainmodelservice
          image: dasb98/domainmodelservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: domainmodels-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: domainmodelservice
  ports:
  - name: domainmodelservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666