apiVersion: v1
kind: Service
metadata:
  name: domainmodelnpservice-srv
spec:
  type: NodePort
  selector:
    app: domainmodelservice
  ports:
    - name: domainmodelservice
      protocol: TCP
      port: 80
      targetPort: 80