# Generated by Django 4.0.1 on 2022-01-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityService', '0002_remove_mobilesensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesensor',
            name='type',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Position', 'Position'), ('Pressure', 'Pressure'), ('Force', 'Force'), ('Humidity', 'Humidity')], default='Temperature', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticsensor',
            name='type',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Position', 'Position'), ('Pressure', 'Pressure'), ('Force', 'Force'), ('Humidity', 'Humidity')], default='Temperature', max_length=20),
        ),
    ]
